---
dependencies: [ ]

galaxy_info:
  author: Tom White, Natalino Busa
  description: Install ands configures Jupyterhub on Redhat/CentOS
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 7
  galaxy_tags:
    - development
