---
raw_data_dirs:
#  - "/home/ftp"
  - /bigdata/skyscannerdata
#  - /bigdata/skyscannersearchdata

mountpoint_dir: "/home/gaston.sanso/backups"
nfs_host: "192.168.1.22"
nfs_share_dir: "/volume1/IT/Backups/raw_data_backups"
nfs_client_mount:
- path: "{{ mountpoint_dir }}"
  src: "{{ nfs_host }}:{{ nfs_share_dir }}"
  opts: rw
  state: present