language: python
versions:
  - "2.7"
  - "3.5"
cache: pip
sudo: required
services:
  - docker

install:
  - pip install -U pip
  - pip --version
  - pip install ansible ansible-lint yamllint flake8 molecule docker
  - ansible-lint --version
  - yamllint --version
  - flake8 --version
  - molecule --version

env:
  - TEST=docker
  - TEST=docker_fedora

script:
  - molecule lint -s openstack
  - molecule test -s "${TEST}"
  - flake8 $(find . -name '*.py')

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
