---
- hosts: all 
  become: yes
  tasks:

  - name: Enable password login
    lineinfile:
      path: /etc/ssh/sshd_config 
      regexp: '^PasswordAuthentication'
      insertafter: '^PasswordAuthentication'
      line: 'PasswordAuthentication yes'

  - name: Restart sshd service
    service: 
      name: sshd
      state: restarted
