---
# Create a new guest using Kickstart

- name: copy over kickstart file
  template: src="kickstart.cfg" dest="{{ runtime_tempdir }}/{{ vm_name }}.ks"
  become: yes
  delegate_to: "{{ hyper }}"
...
