---
# defaults file for sbaerlocher.update-management

## CentOS

update_management_CentOS_enable: true

#  What kind of update to use:
# default                            = yum upgrade
# security                           = yum --security upgrade
# security-severity:Critical         = yum --sec-severity=Critical upgrade
# minimal                            = yum --bugfix update-minimal
# minimal-security                   = yum --security update-minimal
# minimal-security-severity:Critical =  --sec-severity=Critical update-minimal
update_management_update_cmd:
  hourly: 'security'
  daily: 'default'

# Whether a message should be emitted when updates are available,
# were downloaded, or applied.
update_management_update_messages:
  hourly: 'no'
  daily: 'yes'

# Whether updates should be downloaded when they are available.
update_management_download_updates:
  hourly: 'no'
  daily: 'yes'

# Whether updates should be applied when they are available.  Note
# that download_updates must also be yes for the update to be applied.
update_management_apply_updates:
  hourly: 'no'
  daily: 'no'

# Maximum amout of time to randomly sleep, in minutes.  The program
# will sleep for a random amount of time between 0 and random_sleep
# minutes before running.  This is useful for e.g. staggering the
# times that multiple systems will access update servers.  If
# random_sleep is 0 or negative, the program will run immediately.
# 6*60 = 360
update_management_random_sleep:
  daily: 360
  hourly: 15

# Name to use for this system in messages that are emitted.  If
# system_name is None, the hostname will be used.
update_management_system_name: None

# How to send messages.  Valid options are stdio and email.  If
# emit_via includes stdio, messages will be sent to stdout; this is useful
# to have cron send the messages.  If emit_via includes email, this
# program will send email itself according to the configured options.
# If emit_via is None or left blank, no messages will be sent.
update_management_emit_via: stdio

# The width, in characters, that messages that are emitted should be
# formatted to.
update_management_output_width: 80

# The address to send email messages from.
# NOTE: 'localhost' will be replaced with the value of system_name.
update_management_email_from: root@localhost

# List of addresses to send messages to.
update_management_email_to: root

# Name of the host to connect to to send email messages.
update_management_email_host: localhost

# NOTE: This only works when group_command != objects, which is now the default
# List of groups to update
update_management_group_list: None

# The types of group packages to install
update_management_group_package_types:
  - mandatory
  - default

# Use this to filter Yum core messages
# -4: critical
# -3: critical+errors
# -2: critical+errors+warnings (default)
update_management_debuglevel: "-2"

# skip_broken = True
update_management_mdpolicy: "group:main"

# Uncomment to auto-import new gpg keys (dangerous)
# assumeyes: "True"