galaxy_info:
  author: Greg Hellings
  description: >-
    Configure a system to be a good place to build development versions of AWX
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - all

dependencies:
  - role: oasis-roles.system_repositories
    system_repositories_configs: "{{ awx_devel_repositories }}"
